### ISSUE TITLE
Make bucket name configurable

### ISSUE THREAD

**Issue by reisingerf** [umccr/samplesheet-check-frontend#1]
Introduce a parameter, so the bucket name can be configured and is not hard coded in the stack.

https://github.com/umccr/samplesheet-check-frontend/blob/784864c32eeca16b32ac4a585a05ac5b82c7dcfd/cdk/cdk/cdk_stack.py#L13

**Comment by williamputraintan** [comment]
I have changed to use the SSM paramter

**Comment by reisingerf** [comment]
Addressed in 29f2eec5
