### ISSUE TITLE
Integration into portal frontend

### ISSUE THREAD

**Issue by reisingerf** [umccr/samplesheet-check-frontend#4]
Linking samplesheet checker app from portal app and test that auth are working

**Comment by reisingerf** [comment]
The Cognito integration is done, but we still have to link it from the data portal and check that the tokens work across apps.
I'd keep this open until we have done that.

**Comment by williamputraintan** [comment]
The current implementation allows tokens to be used at the portal and the status page at the same time (without the need to re-login). Sometimes might need to re-login when identified that google stored in the browser has multiple accounts and it is on a different app (this includes dev and prod app).
